let suggestions = [
    "Đừng hoài phí tuổi trẻ",
    "Tâm lý học hành vi",
    "Sách đen - Cẩm nang tuyệt mật",
    "Hôm nay phải mở mang",
    "Những bức thư đạo đức",
    "Người trong muôn nghề",
    "Ngành IT có gì?",
    "Phụ nữ độc lập tài chính",
    "Bạn đắt giá bao nhiêu?",
    "Khí chất bao nhiêu, hạnh phúc bấy nhiêu",
    "Đừng lựa chọn an nhàn khi còn trẻ",
    "Càng kỷ luật càng tự do",
    "Ổn định hay tự do",
    "Nghệ thuật giải mã hành vi",
    "Rèn luyện tư duy phản biện",
    "Tâm lý học biểu cảm",
    "Tư duy sâu",
    "Nghệ thuật tập trung",
    "Mọi người đều nói dối",
    "Chó sủa nhầm cây",
    "Tự kỉ ám thị",
    "Tâm lý học nói gì về nỗi đau",
    "Hãy khiến tương lai biết ơn",
    "Tôi nghĩ mọi thứ sẽ ổn",
    "Tôi quyết định sống cho chính tôi",
    "Điều tôi muốn nghe nhất",
    "Lấy người mình yêu, làm điều mình thích",
    "Đời có bao nhiêu, hãy ở bên những người thú vị",
    "Xé vài trang thanh xuân, đổi lấy một bản thân nỗ lực",
    "Kỷ luật tự giác",
    "Sức mạnh của ngôn từ",
    "Hãy ngẩng đầu mà đi",
];
